apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.1
  creationTimestamp: null
  name: certificaterequestpolicies.policy.cert-manager.io
spec:
  group: policy.cert-manager.io
  names:
    categories:
      - cert-manager
    kind: CertificateRequestPolicy
    listKind: CertificateRequestPolicyList
    plural: certificaterequestpolicies
    shortNames:
      - crp
    singular: certificaterequestpolicy
  scope: Cluster
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: CertificateRequestPolicy is an object for describing a "policy profile" that makes decisions on whether applicable CertificateRequests should be approved or denied.
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: CertificateRequestPolicySpec defines the desired state of CertificateRequestPolicy.
              type: object
              required:
                - issuerRefSelector
              properties:
                allowedCommonName:
                  description: AllowedCommonName defines the X.509 Common Name this is permissible. Accepts wildcards "*". An omitted field or value of nil permits all.
                  type: string
                allowedDNSNames:
                  description: AllowedDNSNames defines the X.509 DNS SAN names that may be requested for. Accepts wildcards "*". An omitted field or value of nil permits all. An empty slice `[]` permits nothing.
                  type: array
                  items:
                    type: string
                allowedEmailAddresses:
                  description: AllowedEmailAddresses defines the X.509 URI SAN names that may be requested for. Accepts wildcards "*". An omitted field or value of nil permits all. An empty slice `[]` permits nothing.
                  type: array
                  items:
                    type: string
                allowedIPAddresses:
                  description: AllowedIPAddresses defines the X.509 IP SAN names that may be requested for. Accepts wildcards "*". An omitted field or value of nil permits all. An empty slice `[]` permits nothing.
                  type: array
                  items:
                    type: string
                allowedIsCA:
                  description: AllowedIsCA defines whether it is permissible for the CertificateRequest to contain the field `spec.isCA`. An omitted field or value of nil permits all.
                  type: boolean
                allowedPrivateKey:
                  description: AllowedPrivateKey defines the shape of permissible private keys that may be used for the request. An omitted field or value of nil permits all.
                  type: object
                  properties:
                    allowedAlgorithm:
                      description: AllowedAlgorithm defines the allowed crypto algorithm that is used by the requestor for their private key. An omitted field or value of nil permits all.
                      type: string
                      enum:
                        - RSA
                        - ECDSA
                        - Ed25519
                    maxSize:
                      description: MaxSize defines the maximum key size a requestor may use for their private key. Values are inclusive (i.e. a min value of `2048` will accept a size of `2048`). MaxSize and MinSize may be the same value. An omitted field or value of nil permits all.
                      type: integer
                    minSize:
                      description: MinSize defines the minimum key size a requestor may use for their private key. Values are inclusive (i.e. a min value of `2048` will accept a size of `2048`). MinSize and MaxSize may be the same value. An omitted field or value of nil permits all.
                      type: integer
                allowedSubject:
                  description: AllowedSubject defines the X.509 subject that is permissible. An omitted field or value of nil permits all.
                  type: object
                  properties:
                    allowedCountries:
                      description: AllowedCountries defines the X.509 Subject Countries that may be requested for. Accepts wildcards "*". An omitted field or value of nil permits all. An empty slice `[]` permits nothing.
                      type: array
                      items:
                        type: string
                    allowedLocalities:
                      description: AllowedLocalities defines the X.509 Subject Localities that may be requested for. Accepts wildcards "*". An omitted field or value of nil permits all. An empty slice `[]` permits nothing.
                      type: array
                      items:
                        type: string
                    allowedOrganizationalUnits:
                      description: AllowedOrganizationalUnitsdefines the X.509 Subject Organizational Units that may be requested for. Accepts wildcards "*". An omitted field or value of nil permits all. An empty slice `[]` permits nothing.
                      type: array
                      items:
                        type: string
                    allowedOrganizations:
                      description: AllowedOrganizations defines the X.509 Subject Organizations that may be requested for. Accepts wildcards "*". An omitted field or value of nil permits all. An empty slice `[]` permits nothing.
                      type: array
                      items:
                        type: string
                    allowedPostalCodes:
                      description: AllowedPostalCodes defines the X.509 Subject Postal Codes that may be requested for. Accepts wildcards "*". An omitted field or value of nil permits all. An empty slice `[]` permits nothing.
                      type: array
                      items:
                        type: string
                    allowedProvinces:
                      description: AllowedProvinces defines the X.509 Subject Provinces that may be requested for. Accepts wildcards "*". An omitted field or value of nil permits all. An empty slice `[]` permits nothing.
                      type: array
                      items:
                        type: string
                    allowedSerialNumber:
                      description: AllowedSerialNumber defines the X.509 Subject Serial Number that must be requested for. An omitted field or value of nil permits all.
                      type: string
                    allowedStreetAddresses:
                      description: AllowedStreetAddresses defines the X.509 Subject Street Addresses that may be requested for. Accepts wildcards "*". An omitted field or value of nil permits all. An empty slice `[]` permits nothing.
                      type: array
                      items:
                        type: string
                allowedURIs:
                  description: AllowedURIs defines the X.509 URI SAN names that may be requested for. Accepts wildcards "*". An omitted field or value of nil permits all. An empty slice `[]` permits nothing.
                  type: array
                  items:
                    type: string
                allowedUsages:
                  description: AllowedUsages defines the list of permissible key usages that may appear of the CertificateRequest `spec.keyUsages` field. An omitted field or value of nil permits all. An empty slice `[]` permits nothing.
                  type: array
                  items:
                    description: 'KeyUsage specifies valid usage contexts for keys. See: https://tools.ietf.org/html/rfc5280#section-4.2.1.3      https://tools.ietf.org/html/rfc5280#section-4.2.1.12 Valid KeyUsage values are as follows: "signing", "digital signature", "content commitment", "key encipherment", "key agreement", "data encipherment", "cert sign", "crl sign", "encipher only", "decipher only", "any", "server auth", "client auth", "code signing", "email protection", "s/mime", "ipsec end system", "ipsec tunnel", "ipsec user", "timestamping", "ocsp signing", "microsoft sgc", "netscape sgc"'
                    type: string
                    enum:
                      - signing
                      - digital signature
                      - content commitment
                      - key encipherment
                      - key agreement
                      - data encipherment
                      - cert sign
                      - crl sign
                      - encipher only
                      - decipher only
                      - any
                      - server auth
                      - client auth
                      - code signing
                      - email protection
                      - s/mime
                      - ipsec end system
                      - ipsec tunnel
                      - ipsec user
                      - timestamping
                      - ocsp signing
                      - microsoft sgc
                      - netscape sgc
                issuerRefSelector:
                  description: "IssuerRefSelector is used to match this CertificateRequestPolicy against processed CertificateRequests. This policy will only be evaluated against a CertificateRequest whose `spec.issuerRef` field matches `issuerRefSelector`. CertificateRequests will not be processed on unmatched `issuerRefSelector`, regardless of whether the requestor is bound. Accepts wildcards \"*\". Nil values are equivalent to \"*\", \n The following value will match _all_ `issuerRefs`: ``` issuerRefSelector: {} ``` \n Required field."
                  type: object
                  properties:
                    group:
                      description: Group is the wildcard selector to match the `spec.issuerRef.group` field on requests. Accepts wildcards "*". An omitted field or value of nil permits all.
                      type: string
                    kind:
                      description: Kind is the wildcard selector to match the `spec.issuerRef.kind` field on requests. Accepts wildcards "*". An omitted field or value of nil permits all.
                      type: string
                    name:
                      description: Name is the wildcard selector to match the `spec.issuerRef.name` field on requests. Accepts wildcards "*". An omitted field or value of nil permits all.
                      type: string
                maxDuration:
                  description: MaxDuration defines the maximum duration a certificate may be requested for. Values are inclusive (i.e. a max value of `1h` will accept a duration of `1h`). MaxDuration and MinDuration may be the same value. An omitted field or value of nil permits all.
                  type: string
                minDuration:
                  description: MinDuration defines the minimum duration a certificate may be requested for. Values are inclusive (i.e. a min value of `1h` will accept a duration of `1h`). MinDuration and MaxDuration may be the same value. An omitted field or value of nil permits all.
                  type: string
                plugins:
                  description: Plugins define a set of plugins and their configuration that should be executed when this policy is evaluated against a CertificateRequest. A plugin must already be built within policy-approver for it to be available.
                  type: object
                  additionalProperties:
                    description: CertificateRequestPolicyPluginData is configuration needed by the plugin approver to evaluate a CertificateRequest on this policy.
                    type: object
                    properties:
                      values:
                        description: Values define a set of well-known, to the plugin, key value pairs that are required for the plugin to successfully evaluate a request based on this policy.
                        type: object
                        additionalProperties:
                          type: string
            status:
              description: CertificateRequestPolicyStatus defines the observed state of the CertificateRequestPolicy.
              type: object
              properties:
                conditions:
                  description: List of status conditions to indicate the status of the CertificateRequestPolicy. Known condition types are `Ready`.
                  type: array
                  items:
                    description: CertificateRequestPolicyCondition contains condition information for a CertificateRequestPolicyStatus.
                    type: object
                    required:
                      - status
                      - type
                    properties:
                      lastTransitionTime:
                        description: LastTransitionTime is the timestamp corresponding to the last status change of this condition.
                        type: string
                        format: date-time
                      message:
                        description: Message is a human readable description of the details of the last transition, complementing reason.
                        type: string
                      observedGeneration:
                        description: If set, this represents the .metadata.generation that the condition was set based upon. For instance, if .metadata.generation is currently 12, but the .status.condition[x].observedGeneration is 9, the condition is out of date with respect to the current state of the CertificateRequestPolicy.
                        type: integer
                        format: int64
                      reason:
                        description: Reason is a brief machine readable explanation for the condition's last transition.
                        type: string
                      status:
                        description: Status of the condition, one of ('True', 'False', 'Unknown').
                        type: string
                      type:
                        description: Type of the condition, known values are (`Ready`).
                        type: string
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
